
Vagrant.configure("2") do |config|
  config.vm.hostname = 'vagrant-test'

  config.puppet_install.puppet_version = '6.24.0'
  config.vm.provision :puppet

  config.vm.provision "puppet"

  config.vm.provider "virtualbox" do |v, override|
    override.vm.box = "bento/ubuntu-18.04"
  end

  config.vm.provider "digital_ocean" do |provider, override|
    override.ssh.private_key_path = '~/.ssh/id_rsa'
    override.vm.allowed_synced_folder_types = :rsync
    override.vm.box = 'digital_ocean'
    override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"

    provider.token = ENV['DIGITALOCEAN-TOKEN']  # Remember to set the environment variable DIGITALOCEAN-TOKEN before running
    provider.image = 'ubuntu-18-04-x64'
    provider.region = 'nyc1'
    provider.size = 's-1vcpu-1gb'
    provider.setup = false
  end

  config.vm.define "appserver" do |app|
    app.vm.hostname = "appserver"
  end

  config.vm.define "dbserver" do |db|
    db.vm.hostname = "dbserver"
  end
end
