Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-18.04"

  config.vm.synced_folder "./hosts", "/vagrant/hosts", create: true

  config.vm.provision "shell", inline: <<-SHELL
    wget https://apt.puppetlabs.com/puppet5-release-$(lsb_release -cs).deb
    dpkg -i puppet5-release-$(lsb_release -cs).deb
    apt-get -qq update
    apt-get install -y puppet-agent
  SHELL

  config.vm.provision "puppet" do |puppet|
    puppet.environment_path = "environments"
    puppet.environment = "test"
  end

  config.vm.define "appserver" do |app|
    app.vm.box = "bento/ubuntu-18.04"
    app.vm.hostname = "appserver"
    app.vm.network "public_network", ip: "192.168.0.1", hostname: true
  end

  config.vm.define "dbserver" do |db|
    db.vm.box = "bento/ubuntu-18.04"
    db.vm.hostname = "dbserver"
    db.vm.network "public_network", ip: "192.168.0.2", hostname: true
  end

  config.vm.define "webserver" do |web|
    web.vm.box = "bento/ubuntu-18.04"
    web.vm.hostname = "web"
    web.vm.network "public_network", ip: "192.168.0.3", hostname: true
    web.vm.network "forwarded_port", guest: 80, host: 8080
  end

  tst_server_number = 2

  (0..tst_server_number).each do |i|
    config.vm.define "tst#{i}" do |tst|
      tst.vm.box = "bento/ubuntu-18.04"
      tst.vm.hostname = "tst#{i}"
      tst.vm.network "public_network", ip: "192.168.1.#{i}", hostname: true
    end
  end
end
